name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "reusable-wf-upload-download-artifact" ]

jobs:
  use-reusable-workflow:
    uses: gilbertomaga/github-actions-reusable-wf/.github/workflows/reusable-wf-upload-download-artifact.yml@master
    with:
      build_dir: src
